package address

import (
	"crypto/sha3"
	"encoding/hex"
	"strings"
)

const (
	// EXPLOPrefix is the required prefix for all miner/wallet addresses
	EXPLOPrefix = "explo"

	// AddressLength is the total length of a valid EXPLO address
	// explo (5) + body (40 hex chars from 20 bytes) + checksum (8 hex chars from 4 bytes) = 53
	AddressLength = 53

	// BodyHexLen is the length in hex chars of the address body (20 bytes -> 40 hex chars)
	BodyHexLen = 40

	// ChecksumHexLen is the length in hex chars of the checksum (4 bytes -> 8 hex chars)
	ChecksumHexLen = 8

	// ChecksumBytes is the number of bytes taken from SHA3(core) for the checksum
	ChecksumBytes = 4
)

// GenerateEXPLOAddress generates a valid EXPLO wallet/miner address from a public key.
// Format: "explo" + 40 hex (first 20 bytes of SHA3-256(pubKey)) + checksum (first 4 bytes of SHA3(core) encoded as 8 hex chars)
// Always returns a lowercase string of length 53.
func GenerateEXPLOAddress(pubKey []byte) string {
	// 1) SHA3-256(pubKey)
	hash := sha3.Sum256(pubKey)

	// 2) first 20 bytes -> 40 hex chars
	body := hex.EncodeToString(hash[:20])

	// 3) core = prefix + body
	core := EXPLOPrefix + body

	// 4) checksum = first ChecksumBytes of SHA3(core) -> 8 hex chars
	csHash := sha3.Sum256([]byte(core))
	checksum := hex.EncodeToString(csHash[:ChecksumBytes])

	// 5) final address (lowercase)
	return strings.ToLower(core + checksum)
}

// IsValidMinerID validates a miner/wallet address generated by GenerateEXPLOAddress.
// Expected format: "explo" + 40 hex body + 8 hex checksum = 53 chars total.
func IsValidMinerID(addr string) bool {
	// basic length & prefix checks
	if len(addr) != AddressLength {
		return false
	}
	if !strings.HasPrefix(addr, EXPLOPrefix) {
		return false
	}

	// compute safe indices
	bodyStart := len(EXPLOPrefix)
	bodyEnd := bodyStart + BodyHexLen
	csStart := bodyEnd
	csEnd := csStart + ChecksumHexLen

	if bodyEnd > len(addr) || csEnd > len(addr) {
		return false
	}

	body := addr[bodyStart:bodyEnd]
	checksum := addr[csStart:csEnd]

	// ensure hex validity
	if _, err := hex.DecodeString(body); err != nil {
		return false
	}
	if _, err := hex.DecodeString(checksum); err != nil {
		return false
	}

	// recompute expected checksum
	core := EXPLOPrefix + body
	csHash := sha3.Sum256([]byte(core))
	expected := hex.EncodeToString(csHash[:ChecksumBytes])

	// compare in lowercase
	return strings.ToLower(checksum) == expected
}

// IsValidEXPLOAddress is an exported alias for backward compatibility.
func IsValidEXPLOAddress(addr string) bool {
	return IsValidMinerID(addr)
}
